
  mongoserver:
    build: "mongo/"
    hostname: "mongoserver"
  
      
      
  node1:
    build: "prototype/"
    hostname: "node1"
    volumes:
       - ./prototype/prototype:/usr/src/app


   

    links:
        - mongoserver   
     
  

  node2:
    build: "prototype/"
    hostname: "node2"
    volumes:
       - ./prototype/prototype:/usr/src/app
       
  
         
    links:
        - mongoserver  
   
 
   

  balancer:
    hostname: "balancer.net"
    image: "nginx"
    volumes:
      - ./nginx/:/etc/nginx:ro
      - ./ssl/:/etc/ssl:ro
    links:
        - node1
        - node2


